./local-helper.sh distopt.driver \
--trainFile=data/trainset.dat \
--testFile=data/regr_test.dat \
--numFeatures=100000 \
--numRounds=100 \
--numPasses=1 \
--numSplits=1 \
--lambda=0.001 \
--justCoCoA=true \
--beta=1.0 \
--sgdIterations=100